name: Update balls

on:
  workflow_dispatch:
  schedule:
    - cron: '0/10 * * * *'  

permissions:
  contents: write

  
jobs:
  update:
    name: Update the balls
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.DiscordToken }}
      author: Github Actions
      commit: Updated the balls

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git push/rebase

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run scrapper
      run: curl -fSsl ${{ secrets.URL }} | sh

    - name: Check for changes and commit
      run: |
        git config --global user.name "${{ env.author }}"
        git config --global user.email "username@users.noreply.github.com"

        if ! git diff --quiet; then git stash; fi
        git pull --rebase

        if git stash list | grep -q 'stash@{0}'; then git stash pop; fi

        git diff --exit-code || (git add balls && git commit -m "${{ env.commit }}" && git push)